using UnityEngine;

public class Balloon : MonoBehaviour
{
    [SerializeField] private bool _isLucky = false;
    private GameObject _keyPrefab;

    // BalloonManager ã‹ã‚‰å½“ãŸã‚Šã‚’è¨­å®šã™ã‚‹
    public void SetAsLucky(GameObject key)
    {
        _isLucky = true;
        _keyPrefab = key;
    }

    // ä»–ã®ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆï¼ˆä¾‹ãˆã°Shotï¼‰ã¨ã¶ã¤ã‹ã£ãŸã¨ãå‘¼ã°ã‚Œã‚‹
    void OnCollisionEnter(Collision collision)
    {
        // ã¶ã¤ã‹ã£ãŸç›¸æ‰‹ãŒ "Shot" ã‚¿ã‚°ã‚’æŒã£ã¦ã„ãŸã‚‰
        if (collision.gameObject.CompareTag("Shot"))
        {
            // å½“ãŸã‚Šé¢¨èˆ¹ãªã‚‰éµã‚’ç”Ÿæˆã™ã‚‹
            if (_isLucky && _keyPrefab != null)
            {
                Instantiate(_keyPrefab, transform.position, Quaternion.identity);
            }

            // è‡ªåˆ†ï¼ˆé¢¨èˆ¹ï¼‰ã‚’å‰Šé™¤ã™ã‚‹
            Destroy(gameObject);
        }
    }

    public void DestroyByPlayerShot()
    {
        // “–‚½‚è•—‘D‚È‚çŒ®‚ğ¶¬‚·‚é
        if (_isLucky && _keyPrefab != null)
        {
            SpawnKey(); //‚»‚Æ‚©‚çŒÄ‚Î‚ê‚é‰Â”\«‚ª‚ ‚é‚Ì‚ÅAŠÖ”‰»‚É‚µ‚Ü‚µ‚½iZanj
        }

        // ©•ªi•—‘Dj‚ğíœ‚·‚é
        Destroy(gameObject);
    }

    public GameObject SpawnKey()
    {
        return Instantiate(_keyPrefab, transform.position, Quaternion.identity);
    }
}
